//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Volunteer_Overseas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Applications = new HashSet<Application>();
            this.Project_Carousel_Image = new HashSet<Project_Carousel_Image>();
            this.Project_Cost = new HashSet<Project_Cost>();
            this.Project_Include_Check = new HashSet<Project_Include_Check>();
            this.Project_Start_Date = new HashSet<Project_Start_Date>();
            this.Project_View_History = new HashSet<Project_View_History>();
        }
    
        public int id { get; set; }
        public int organization_id { get; set; }
        public int activity_id { get; set; }
        public int category_id { get; set; }
        public string title { get; set; }
        public string overview_description { get; set; }
        public string accomodation_description { get; set; }
        public string impact_description { get; set; }
        public string project_video { get; set; }
        public int city_id { get; set; }
        public int country_id { get; set; }
        public string volunteer_house_address { get; set; }
        public string volunteer_work_address { get; set; }
        public string nearest_airport_address { get; set; }
        public string cost_description { get; set; }
        public int min_age { get; set; }
        public int max_age { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public int status { get; set; }
        public string main_image { get; set; }
        public string start_date_description { get; set; }
    
        public virtual Activity Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Carousel_Image> Project_Carousel_Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Cost> Project_Cost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Include_Check> Project_Include_Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Start_Date> Project_Start_Date { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_View_History> Project_View_History { get; set; }
    }
}
